[tox]
envlist = lint,black,isort,py{37, 310}-pytest{6, 7},coverage
setenv = PYTHONIOENCODING = UTF-8

[testenv]
deps =
  pytest6: pytest>6<7
  pytest7: pytest>7<8
  -rrequirements.dev.txt
commands =
  coverage run -m pytest

[testenv:py310-pytest{0, 1}]
depends = lint, black

[testenv:lint]
basepython = python3.10
deps =
  -rrequirements.dev.txt
commands =
  pylint  pytest_rerunfailures.py

[testenv:black]
basepython = python3.10
skip_install = true
deps =
  black
commands =
  black --check .

[testenv:isort]
basepython = python3.10
skip_install = true
deps =
  isort
commands =
  isort --check .

[testenv:coverage]
skip_install = true
parallel_show_output = true
whitelist_externals = rm
depends = py{37,310}-pytest{6,7}
deps =
  coverage
commands =
  coverage combine
  coverage report
  coverage html
  coverage xml
  rm .coverage

[pytest]
addopts = --junitxml ./testResults.xml
